name: Pixular Automaton
description: A cellular automaton mess.
url: https://jfenn.me/pixularautomaton
baseurl: "/"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

sass:
    sass_dir: ./css
