name: Pixular Automaton
description: An image generating mess.
url: https://jfenn.me/imagerator
baseurl: "/"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

sass:
    sass_dir: ./css
